### ISSUE TITLE
Nothing happends

### ISSUE THREAD

**Issue by K4stor** [stevensona/shader-toy#10]
Hi 

I have the extension installed, I added a test shader, opened the extension, and the preview stays blank and no error is shown in the console.

![screen shot 2017-02-21 at 11 21 39](https://cloud.githubusercontent.com/assets/1078043/23160805/2af6f314-f828-11e6-8a44-c497f5e2dcbd.png)

**Comment by stevensona** [comment]
Thanks for taking time to report the issue. Which platform is this on?

**Comment by K4stor** [comment]
Hello, 

its happening on mac os sierra. Is there anything I can do to help you find the issue ?

**Comment by stevensona** [comment]
Yeah this one's got me stumped at the moment. It doesn't work on my mac os sierra anymore either. I'm not sure if something in vscode or chromium changed to break it. Still works on Windows and will investigate more when I get a chance.

**Comment by K4stor** [comment]
Thanks !

**Comment by stevensona** [comment]
@K4stor Thanks to @voppe, this issue should be fixed (works on my mac at least)! Please update, and let me know how it goes!

**Comment by K4stor** [comment]
thanks so much guys !! I works like a charm now
