### ISSUE TITLE
Including file with same name

### ISSUE THREAD

**Issue by 57ar7up** [stevensona/shader-toy#105]
Example:
file `1.glsl` can't include file `folder/1.glsl`

**Comment by Malacath-92** [comment]
A fix for this is on its way.
Though I would still advise against this, it's kinda confusing and in any project I worked on it was considered bad practice to have multiple files with the same name. Not judging, just saying what I experienced  :)

**Comment by 57ar7up** [comment]
Yeah, I can see, but I still think it's logically valid thing to do. Not in last case (discovered randomly), but generally my naming scheme is universal and repeating to the end. Probably will work bad with team

**Comment by Malacath-92** [comment]
Yeah, it's valid of course. Hence the fix in that PR  :)
