### ISSUE TITLE
[Feature Request] Disable automatic recompilation

### ISSUE THREAD

**Issue by Kowbell** [stevensona/shader-toy#115]
It would be nice to make the auto-recompile feature optional. Having your computer constantly watching file changes and triggering recompilation isn't always desirable, especially if you're on battery power, your laptop chassis is the heat sink, you're working on a shader that takes inexplicably long to compile (written by some one else, of course 😉.)

I imagine the most flexible approach would be to add some command palette option to allow users to switch between having the preview recompile when they've changed the previewed file, only when they've _saved_ the file, or only manually via some other command/a "recompile" button over the preview next to play/pause.

**Comment by Malacath-92** [comment]
I agree this could be more felxible, but the option to disable it or modify the timeout already exists:
![image](https://user-images.githubusercontent.com/30243536/93719783-146aff00-fb85-11ea-97fd-c23110f06143.png)
Adding more options for reloading, specifically disabling all automatic reloading and replacing it with a reload button (which is exactly what the online version of shader-toy does) sounds like a good idea.
