### ISSUE TITLE
Show GLSL Preview not working

### ISSUE THREAD

**Issue by Hendiadyoin1** [stevensona/shader-toy#117]
On the latest version of vsCode (1.50.1) the command to open the preview is not working:
> Command 'Shader Toy: Show GLSL Preview' resulted in an error (command 'shader-toy.showGlslPreview' not found)

**Comment by Hendiadyoin1** [comment]
The version 0.10.12 works for me but 0.10.13 does not seem to work

**Comment by Malacath-92** [comment]
'tis no good. I'll take a look soon.
Thanks for letting us know  :pray:
