### ISSUE TITLE
[feature request] VFlip control for texture

### ISSUE THREAD

**Issue by jcyuan** [stevensona/shader-toy#126]
for example:

#iChannel0::FlipY false

to match the functionality on shadertoy:
![image](https://user-images.githubusercontent.com/850854/102954218-f4453600-450d-11eb-86b4-03c89a20c7ed.png)

thanks!

**Comment by Malacath-92** [comment]
Can elaborate what this checkbox does? Does it really just vertically flip the texture?
If so I don't quite understand why this is necessary, shouldn't it be simple to just write a function that flips the texture coordinates on sampling?

**Comment by jcyuan** [comment]
https://www.shadertoy.com/view/4sdfz8

for example, at line 17, fetch hash from texture to generate noise, if without this flip value, the result is wrong.
yes of course we can do something to avoid this option, but it's actually handy, and it just matches the shadertoy function so easy to publish to shadertoy once finished in VSC, or copy shader code from shadertoy into VSC to analyze.
this option i think controls the GL function `glTexParameteri(gl.flipY, true/false)`.

thanks.

**Comment by jcyuan** [comment]
one year past, close as no reply.
