### ISSUE TITLE
Feature request: export as video

### ISSUE THREAD

**Issue by skypyxis** [stevensona/shader-toy#153]
A great addition would be to be able to export the result as a video file

**Comment by 589290** [comment]
Absolutely! This VScode extension appears to run just about every GLSL shader possible. 

Currently, I've been using https://github.com/polyfloyd/shady and https://github.com/danilw/shadertoy-to-video-with-FBO but both of these tools don't work with a great deal of shaders.

**Comment by altunenes** [comment]
I was looking for this feature :=) Capturing frames as png could be also good for creating h res videos with FFmpeg :=))))

**Comment by 589290** [comment]
@Malacath-92 would it be possible to allow the user to set the fps (framerate) that you hardcoded here: https://github.com/stevensona/shader-toy/pull/165/commits/a6e765d1ccf4a382cbb57c1a5e0259a2f6f59e7d#diff-ecf15ea18da90e8c77dff30f58aab5bdbf7de703ea34240d41527be44c176688R459 to 30fps? Perhaps in a settings page?

**Comment by Malacath-92** [comment]
I added the option, I don't think it is a guarantee tho with the web api from my short tests.

**Comment by 589290** [comment]
I agree with your opinion, there's a lot of things in the browser engine than can cause **jank** and make the canvas record operation miss the target framerate. This has been my experience working with it in the past. However, I still believe it will  be useful to record certain shaders w/ low fps values and others w/ higher values. 

Thank you for smashing this out! Eagerly awaiting your change to hit stable.

**Comment by Malacath-92** [comment]
I'll be on vacation for 4 weeks so I'll publish this now. Please just report any issues as usual, if there are serious bugs I will find the time to fix them.

**Comment by 589290** [comment]
The recording function works extremely well for every shader I threw at it! Very nice work!

However, I did not see the option for adjusting the framerate, perhaps in the next release?

One small bug : https://github.com/stevensona/shader-toy/issues/172
