### ISSUE TITLE
0.4.0 can not loadTexture,screen blank

### ISSUE THREAD

**Issue by yafacex** [stevensona/shader-toy#16]
my os is win7,0.4.0 can not loadTexture in my pc.

**Comment by stevensona** [comment]
Please show the code, as well as your workspace's settings.json file

**Comment by yafacex** [comment]
code:
void main(){
    vec2 uv = (gl_FragCoord.xy/iResolution.xy);
    uv.y += .05 * sin(iGlobalTime + uv.x * 10.);
    uv.x += .05 * sin(iGlobalTime + uv.y * 10.);
    vec4 color = texture2D(iChannel0,uv);
    gl_FragColor = color;
    // gl_FragColor = vec4(0,0,1,1);
}

config file in .vscode/settings.json:

{
    "shader-toy.textures": {
        "0": "./perlin.png",
        "1": "./duck.png"
    }
}
the two textures above are in my workspace root

Through vscode developer tools' console,i got the log:
.Offscreen-For-WebGL-082BF4D8]RENDER WARNING: there is no texture bound to the unit 0
I have tried preview.html in chrome,it performs well. But on vscode(version 1.12.2 on windows),it broken.

**Comment by hbflyhbfly** [comment]
hi,Ihave the same question.
The local texture can't loaded.
![qq20170727-185931](https://user-images.githubusercontent.com/3788918/28667357-c229c89c-72fd-11e7-9597-7c4048c9863d.png)
**setting.json**:
{
    "shader-toy.textures": {
        "0": "./role_2.png",
        "1": "https://66.media.tumblr.com/tumblr_mcmeonhR1e1ridypxo1_500.jpg"
    }
}
**glsl**:
vec2 focus = vec2(.5,.5);

const float split_num = 10.;

float radius = 0.1;


void main()
{
	vec2 uv = (gl_FragCoord.xy / iResolution.xy);
  gl_FragColor = texture2D(iChannel0, uv);
}

**Comment by vadim-kudr** [comment]
use absolute path like file:///Users/user/dev/gl/0.jpg

**Comment by Malacath-92** [comment]
Relative paths should be supported as long a workspace is opened.

**Comment by krauspe** [comment]
I tried both 
1. using settings file with relative path , while having open folder in vscode

{
    "shader-toy.textures": {
        "0": "file://./iChannel0.png",
        "1": "file://./iChannel1.png",
        "2": "file://./iChannel3.png",
        "3": "file://./iChannel3.png"
    }
}

2.  Using declaration in shader code which shoould be enabled by default due to documentation

#iChannel0 file://./iChannel0.png

Nothing worked ! Whats wrong ?

**Comment by Malacath-92** [comment]
@krauspe I assume you are on the newest version 0.7.10
I'm on Windows 10 and the second version works fine for me. A sample code would be:
```glsl
#iChannel0 file://./image.png

void main() {
    vec2 uv = gl_FragCoord.xy / iResolution.xy;
    gl_FragColor = texture(iChannel0, uv);
}
```
Is your image file really called `iChannel0.png`? Are you sampling the texture correctly, e.g. with correct UV-coordinates as the example does? Are you sure you opened the folder containing your image files? You see that if on top of your screen, between `Visual Studio Code` and the opened text editor it says the name of your folder. In the example it says `shader-toy-bug`:
![example](https://user-images.githubusercontent.com/30243536/54747129-4edd8f80-4bce-11e9-9ea6-87ed95d18817.PNG)

Can I see your code in case this doesn't help?

**Comment by krauspe** [comment]
@Malacath-92 , yes the names are indeed iChannell0.png , iChannel1.png etc
and yes I'm staying in the folder where everything is located, the shader file ans the pics

Her's my first code snippet:
----- snip -----------------

// Created by inigo quilez - 2015
// License Creative Commons Attribution-NonCommercial-ShareAlike 3.0
#iChannel0 file://./iChannel0.png
#iChannel1 file://./iChannel1.png
#iChannel2 file://./iChannel3.png
#iChannel3 file://./iChannel3.png

Can I attach pictures here ?

**Comment by Malacath-92** [comment]
@krauspe I think if you drag and drop an image onto your post it will upload to your users content. But you don't need to attach images, I can place my own for testing. Unless your images are broken of course  😃

**Comment by krauspe** [comment]
@Malacath-92 , I should mention that I just tried to adapt stuff from shadertoy  containg shaders with texture files. 

I wanted to study the snail (https://www.shadertoy.com/view/ld3Gz2)
Meanwhile I found that I used a somewhat modified version 

Now tried the original and voila: everything works fine !
However, thanks for helping and sorry for bothering !

I should have tried a simpler example first :-)

**Comment by Malacath-92** [comment]
Alright, this issue is outdated (opened for version 0.4.0) and doesn't seem relevant anymore. So I'll close it and if someone has an issue in the current version they'll open a new one.
