### ISSUE TITLE
Audio channels

### ISSUE THREAD

**Issue by stevensona** [stevensona/shader-toy#17]
Similar to Shadertoy.com, support audio channels as inputs into shaders.

Suggested by @edap

**Comment by MacroMachines** [comment]
I advise checking out integrating the interactiveshaderformat.com git, they have some very useful things including audio FFT and json for uniforms and render layers as well as many other nice additions in their open source spec

**Comment by stevensona** [comment]
0.8.4 (just released) adds experimental support for this #48 Thanks to @Malacath-92

**Comment by Malacath-92** [comment]
Closing this because what we have right now is as close as we can get with what vscode will officially support within a webview.
