### ISSUE TITLE
Feature request: Export Frames as PNG for High-Resolution Video Creation

### ISSUE THREAD

**Issue by altunenes** [stevensona/shader-toy#173]
Currently, the extension supports recording shaders in the `webm `format.

Wouldn't it be nice if we had a feature that allows users to export individual frames as PNG images at a desired resolution? This would facilitate creating high-quality videos, even up to 4K resolution, by post-processing these frames with tools like ffmpeg.
 
This feature request is inspired by the implementation in [shadertoy-exporter](https://github.com/KoltesDigital/shadertoy-exporter/blob/master/app/browser/app/shadertoy/export-frames.js).

**Comment by shadielhajj** [comment]
Hi. I just submitted a PR which implements high-quality offline recording. WEBM, PNG, GIF and JPG are supported.
The PR also adds settings to configure resolution, frame-rate, quality, etc...
Offline rendering means no frames are dropped, independently of hardware capabilities.

https://github.com/stevensona/shader-toy/pull/181
