### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by DomDomHaas** [stevensona/shader-toy#2]
Hi there :)

Well showing compile errors would be great. Or at least highlighting the line which has a problem.

**Comment by stevensona** [comment]
I totally agree. I am currently working out a way to redirect the output from the TextDocumentContentProvider interface into the workspace.

**Comment by stevensona** [comment]
0.1.6 adds basic support for error output. It currently displays the list of GLSL compiler errors in the output view. It's not perfect, but it's certainly better than before.
![errors](https://cloud.githubusercontent.com/assets/431691/17080435/50228b44-50fd-11e6-8372-90f3e500ce77.png)

**Comment by Malacath-92** [comment]
The extensions currently also hyperlinks to reveal the line that the error happens on. The error output will probably not get better for now.
