### ISSUE TITLE
Can't Open “GLSL Preview”: Cannot read property 'document' of undefined. 

### ISSUE THREAD

**Issue by CyangYu** [stevensona/shader-toy#20]
This message from VS Code. My System is "Manjaro Linux", The mesa version is 3.0 Mesa 17.3.8

**Comment by Malacath-92** [comment]
Is this a problem in the current version? And is it reproducible for you?

**Comment by Malacath-92** [comment]
This issue seems outdated, if it still exists we will hopefully get a new issue opened.
