### ISSUE TITLE
GUI breaks dramatically when window is resized 

### ISSUE THREAD

**Issue by Malacath92** [stevensona/shader-toy#29]
The issue looks to much of the gui having a wrong set of UVs, text seems to continually work as expected.

No know way to reproduce as off now.

**Comment by Malacath92** [comment]
@stevensona I totally goofed and created an issue on the wrong project. Can you do me the favour and delete this one?

**Comment by stevensona** [comment]
@Malacath92 Github doesn't support deleting issues, but I'm not worried about it.
