### ISSUE TITLE
Can't LOAD the TEXTURE!

### ISSUE THREAD

**Issue by daiday** [stevensona/shader-toy#5]
my glsl code is :

void main()
{
    gl_FragColor = texture2D(iChannel0, gl_FragCoord.xy);
}

and my folder is:
.vscode
test.glsl
normalmap_2.png

my settings.json is:

{
        "shader-toy.textures": {
        "0": "./normalmap_2.png"
    }
}

BUT, I can't see the image anywhere! and the image is power of two...
please help me...

**Comment by stevensona** [comment]
Thanks, currently investigating.

**Comment by stevensona** [comment]
The root cause for this regression is still under investigation. For the time being, if you use texture resource not on the local machine, it will load and render correctly. For example:
```cpp
void main()
{
  vec2 uv = (gl_FragCoord.xy / iResolution.xy);
  gl_FragColor = texture2D(iChannel0, uv);
}
```
```json
{
  "shader-toy.textures": {
  "0": "http://placehold.it/512x512"
  }
}
```

**Comment by daiday** [comment]
Sorry.... I use the wrong UV.... first time write the pixel shader without vertex shader...
 Thanks for your help, and I use the FULL DIRECTIONARY PATH NAME, it works,and the network path works too.
thanks!
