### ISSUE TITLE
Version 0.8.4 on Mac 10.14.4 doesn't work.

### ISSUE THREAD

**Issue by AdamWang1102** [stevensona/shader-toy#51]
After upgrade to 0.8.4 my Shadertoy Preview doesn't work and always prompt me "Can't found shader-toy command" even I **reinstall the extension** and **reinstall VSCode**. When I downgrade to 0.8.3 extension works fine.

My OS is Mac 10.14.4 and VSCode version is 1.34.0
![image](https://user-images.githubusercontent.com/5875393/58405375-dd243500-8099-11e9-849e-d92d5c25b377.png)
How can I fix this?

**Comment by Malacath-92** [comment]
Can confirm, this also happens on Windows.
@stevensona Could this be related to dependencies not being installed correctly?

**Comment by Malacath-92** [comment]
@stevensona Yes, quite surely this is the problem. Some dependencies should be move from "devDependencies" to "dependencies". Quite honestly I have no idea how to test which dependencies need to be moved. Do you know how to go about this?
@AdamWang1102 Manually running `npm install` inside ".vscode\extensions\stevensona.shader-toy-0.8.4\" will fix the issue temporarily. I don't know where to find that folder on MacOS, but I'm sure it will not be too difficult.

**Comment by stevensona** [comment]
It is (most likely) the new dependencies "mime" and "compare-versions".

**Comment by Malacath-92** [comment]
Can confirm, it's those two.

**Comment by stevensona** [comment]
Reopening until I can release new version.

**Comment by AdamWang1102** [comment]
@Malacath-92 @stevensona Thank you guys, after run ```npm install ```  0.8.4 works fine now. By the way in Mac the path is `~/.vscode/extensions/stevensona.shader-toy-0.8.4`

**Comment by stevensona** [comment]
Thanks everyone 😁
