### ISSUE TITLE
missing variable "iGlobalTime" recently

### ISSUE THREAD

**Issue by villain749** [stevensona/shader-toy#57]
As of the last few weeks ,  June 2019, I noticed none of my shaders work. They all complain that the variable "iGlobalTime" is not defined. 
I am using the 64 bit version on Windows 10.
Any help would be most welcomed
Thanks,
sj

**Comment by Malacath-92** [comment]
This is an embarrassing type on my part  😢 
In the meantime, can you use `iTime` or the following?
```
#ifdef SHADER_TOY
#    ifndef iGlobalTime
#        define iGlobalTime iTime
#    endif
#endif
```

@stevensona It's gonna take you five seconds to fix this and I won't have the chance for it r/n.
https://github.com/stevensona/shader-toy/blob/a9185ef42c0e5453a555860e8cf30f0ec99cad00/src/webviewcontentprovider.ts#L46-L47

**Comment by villain749** [comment]
This fix worked perfectly, Thank you. 
Since you people probably don't get enough credit I would like to heap some praise on you. At my previous job we were not allowed internet access due to MPAA regulations.. so no ShaderToy. Your software gave me a canvas to test out new ideas, and even show my superiors a visual prototype of what I was planning to do next. You made my life so much easier. Thank you very much.

**Comment by stevensona** [comment]
Okay this one is fixed and released.

Thank you @villain749 for your kind words. I am stoked to see that this thing is used and beneficial to people. @Malacath-92 does all of the work around here, and I'm super glad he's on the team he does a great job. Thanks! 😁

**Comment by Malacath-92** [comment]
I can only agree with @stevensona, I'm really happy that people are appreciating the work we do here  😃
