### ISSUE TITLE
Off-Topic for Adam Stevenson

### ISSUE THREAD

**Issue by konung** [stevensona/shader-toy#6]
Hi Adam
This is not a SPAM message. 

My name is Nick Gorbikoff - I'm an it director over at AJR International, a company in Glendale Heights, IL . We got your resume through indeed.com and tried to contact you, but I'm guessing it went to SPAM. 
If you are still interested in a Ruby Developer position, please reach out to me
-------------------------
Kind Regards,

Nick Gorbikoff
IT Director

AJR International
300 Regency Drive
Glendale Heights, IL 60139

t: (630) 832-0222 x 242
f: (630) 832-0333
e: ngorbikoff@ajrintl.com
w: www.ajrintl.com

**Comment by stevensona** [comment]
Responded via email
