### ISSUE TITLE
Audio input not work with Visual Code 1.35.1

### ISSUE THREAD

**Issue by leidd** [stevensona/shader-toy#63]
I had update my Visual Code to 1.35.1, and update the Shader Toy plugin to 0.8.8, 
and then I open the audio input setting, put the mp3 to the right place(if path is not correct, it will notice what went wrong),but when i preview with the shader, the audio input  channel still not work, and has none error or notice. From the issue i know it added from 0.8.4, so if i want to  experience, What shall I do?

**Comment by stevensona** [comment]
Have you checked the "Enable Audio Input" setting?

**Comment by Malacath-92** [comment]
Audio input works for me.

If you have audio input disabled it should emit a warning when you use audio input. But it's worth checking that you do have it enabled for sure.
If it is enabled and not working, can you try executing the "Developer: Open Webview Developer Tools" (on Windows pressing Ctrl-Shift-P, start typing the command and select it when it appears). see if there is any pertinent information logged.
What file-type are you using? It could be that is is either not supported by the Web Audio implementation in Chromium or it's not recognized as an audio file by the mime library your using.

**Comment by Malacath-92** [comment]
@leidd can you check what we mentioned in our two replies above? Otherwise we will have to close the issue since we have no information to go on.

**Comment by leidd** [comment]
The audio input setting had enabled,
![image](https://user-images.githubusercontent.com/8455033/60945912-6b3d3d80-a31f-11e9-9d84-f682e6f9c22c.png)
![image](https://user-images.githubusercontent.com/8455033/60945942-8314c180-a31f-11e9-9e5f-f976c45f6d55.png)
And then I Open Webview Developer Tools, it show errors
![image](https://user-images.githubusercontent.com/8455033/60946854-e69fee80-a321-11e9-8cc4-ced9043344da.png)

**Comment by Malacath-92** [comment]
@leidd this is weird. As long as you're using a local file I don't see why this would happen. Is it possible for you to upload the file so I can do some more debugging.

**Comment by leidd** [comment]
I used the mp3 in this project, it shows the same error, My operating system is MacOS, is there a problem? And the project struct like this
![image](https://user-images.githubusercontent.com/8455033/60951217-3b943280-a32b-11e9-9de4-ea8dd4e52ffd.png)

**Comment by Malacath-92** [comment]
It could be a Mac OS specific bug, but I have no way of testing that right now. I'll try to recreate your setup to see if there might be a more general issue.

**Comment by leidd** [comment]
Thanks, I will continue to focus on this

**Comment by Malacath-92** [comment]
I now have the same issues on my windows machine. Maybe last time I tried I didn't have an updated VSCode version. I'm kinda stumped how to prevent this problem though.

**Comment by leidd** [comment]
OK，I can just wait for your update, that's what i can do now ^_^

**Comment by Malacath-92** [comment]
This issue definitely was introduced in the June update of VSCode, I will try to mention the issue on their repo.

**Comment by Malacath-92** [comment]
Refer to [this issue](https://github.com/microsoft/vscode/issues/78333)
It looks like it is a bug with the current bundled chrome version. I tested the exploration build, which bundles electron 6, where I do not experience the issue anymore. I'm sorry about this, but from what I can see there is nothing we can do on our side to work around this.

**Comment by markus-wa** [comment]
I'm still having this issue on the latest VS Code version. It seems it wasn't fixed by https://github.com/microsoft/vscode/issues/78333.

Can anyone confirm that it works for them on VS Code 1.41.1?

**Comment by Malacath-92** [comment]
This is on my todo list after our next release. But right now it looks to me like the information I was given was incorrect/incomplete and the insiders build ships with a different version of Electron than the Insiders build that I was instructed to use, namely ffmpeg was stripped from the main release. Also on the most recent Insiders build the audio input does not work, so I assume they unified that across version. Not sure if we can do anything about this, other than go back to the older version.
I also plan to add a feature that lets users export their shaders to a portable html file, and those could support audio, given the browser used to display them supports the web audio api.
I'll post here if I learn more.

**Comment by markus-wa** [comment]
Unfortunate to hear. But thanks for the update 🙂

**Comment by ChrisProlls** [comment]
Any news about this ? The issue in the VS Code repo seems closed and I can't ask for news ...

**Comment by Malacath-92** [comment]
@ChrisProlls See my post from last week, I am under the impression now that VSCode will not support this anytime soon, if ever. I will investigate after our next release.

**Comment by Malacath-92** [comment]
Closing this, since it is not within the scope of this extension. An export to a portable html file is now available, though most likely it's necessary to host a server locally in order to open the file in modern browsers (since they shouldn't allow reading local files that easily)
