### ISSUE TITLE
is it possible to support glslify in this great package?

### ISSUE THREAD

**Issue by shengsword** [stevensona/shader-toy#64]

**Comment by Malacath-92** [comment]
Looks feasible, I will take a look at it as soon as I can.

**Comment by Malacath-92** [comment]
Looks like supporting it is quite simple, however it doesn't support mapping lines from post-transform to pre-transform. So I'll disable it by default and remove any of the line information from the error output if it is enabled, which is a shame. I'll consider opening an issue on the glslify page in the future.

**Comment by shengsword** [comment]
Wow, it still be very useful if glslify is working in shader-toy though a little deficiency there
