### ISSUE TITLE
iChannel0 use file://glsl error

### ISSUE THREAD

**Issue by lance-loong** [stevensona/shader-toy#69]
use glsl file to iChannel, not show every image

**Comment by Malacath-92** [comment]
Can you be more clear what you mean and possibly give some code examples? I unfortunately don't understand what you mean.

**Comment by nickkuk** [comment]
If I understand correctly, I have the same behavior. The following example works in 0.8.8, but doesn't work in 0.8.9:

buffer0.glsl:
```glsl
void mainImage(out vec4 color, in vec2 coord) {
  vec2 uv = coord/iResolution.xy;
  vec3 col = 0.5 + 0.5*cos(iTime+uv.xyx+vec3(0,2,4));
  color = vec4(col, 1.0);
}
```

main.glsl:
```glsl
#iChannel0 "file://./buffer0.glsl"

void mainImage(out vec4 color, in vec2 coord) {
  vec3 c = texelFetch(iChannel0, ivec2(coord), 0).xyz;
  color = vec4(c, 1.0);
}
```

**Comment by lance-loong** [comment]
yes,nickkuk is right.

**Comment by Malacath-92** [comment]
Alright, I see that that's not the wanted behaviour. I'll take a look when I get home.

**Comment by lance-loong** [comment]
thank very much

**Comment by lizhiqi-coder** [comment]
I have the same behavior , use glsl file to iChannel, not work
