### ISSUE TITLE
Type mismatch on forceAspectRatio

### ISSUE THREAD

**Issue by matcool** [stevensona/shader-toy#76]
I'm trying to force the aspect ratio to be 16:9 (with `"shader-toy.forceAspectRatio": [16, 9]`), but I get the warning
```
Incorrect type. Expected one of number, number.
```
Edit: Shader still works fine, this is a very minor issue

**Comment by Malacath-92** [comment]
I assume you mean the error reported in the `settings.json`? I've noticed this for a while but always assumed there is some error in the json parsing, since it still works. It does also work for you, right?
Either way, I think it is better that I take a closer look to see if I can fix this.
