### ISSUE TITLE
Unable to open 'GLSL Preview': Cannot read property 'document' of undefined.

### ISSUE THREAD

**Issue by RoganMurley** [stevensona/shader-toy#8]
When running `Show GLSL Preview` from the command palette I get the following error:

`Unable to open 'GLSL Preview': Cannot read property 'document' of undefined.`

**Comment by stevensona** [comment]
Rogan,
Can you tell me a bit more about how you're using it or provide a screenshot? You must use the command `Show GLSL Preview` with a GLSL document open.

**Comment by noxo** [comment]
<img width="1392" alt="screen shot 2017-02-09 at 20 30 07" src="https://cloud.githubusercontent.com/assets/714768/22797387/b3e08dfa-ef06-11e6-9013-d77ab24be618.png">
I've same issue with Visual Studio Code & Mac..

**Comment by stevensona** [comment]
Thanks @noxo for posting the screenshot. When I get a chance, I'll look into it.

**Comment by stevensona** [comment]
#11 fixed this.
