### ISSUE TITLE
Bundle extension

### ISSUE THREAD

**Issue by stevensona** [stevensona/shader-toy#83]
Just making a note that when publishing extension we receive the following message:

> This extension consists of 797 separate files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore

**Comment by Malacath-92** [comment]
Huh, that sounds relevant  :D
I'll take a look at that when I have time this week.
