### ISSUE TITLE
Unable to set filters for images due to error

### ISSUE THREAD

**Issue by Cipheroid** [stevensona/shader-toy#86]
> To influence the sampling behaviour of a texture, use the following syntax:
> #iChannel0::MinFilter "NearestMipMapNearest"
> #iChannel0::MaxFilter "Nearest"
> #iChannel0::WrapMode "Repeat"

Expected texture parameter keyword after "::" but got "MaxFilter"
#iChannel0::MaxFilter "Nearest"

**Comment by Malacath-92** [comment]
It looks like the setting is called "MagFilter" instead of "MaxFilter", I will fix that in the readme for the next release.

**Comment by Malacath-92** [comment]
I will also clarify in the error message what are the valid options.
@Cipheroid For now you are the only one that knows that this is the correct way to do it  :P
```
#iChannel0::MagFilter "Nearest"
```
