### ISSUE TITLE
Preview tab takes focus every recompile if using #iChannel

### ISSUE THREAD

**Issue by ostwilkens** [stevensona/shader-toy#90]
If I add `#iChannel0 "file://noise.png"` to my shader, the GLSL Preview tab takes focus whenever recompiling the shader. 
This means any keyboard input causes loss of focus, rendering the feature unusable. 
I have used channels before without a problem, so this is probably caused by a recent change to the plugin or to VS Code.

**Comment by Malacath-92** [comment]
That sounds like an issue deserving a hotfix. Thank you for bringing it to our attention  :)
I'll have a look when I'm done with work today
