### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Itachi546** [stevensona/shader-toy#92]
- Issue Type: `Performance`
- Extension Name: `shader-toy`
- Extension Version: `0.10.3`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\lenovo\stevensona.shader-toy-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Malacath-92** [comment]
Is it possible for you to link your cpuprofile.txt file?

**Comment by Malacath-92** [comment]
I tried to run a performance test myself and I didn't manage to get the extension to be unresponsive. So maybe you can also provide some context of what kind of shaders you were working with, how you were working and when the unresponsiveness happens.

**Comment by Malacath-92** [comment]
@Itachi546 can you please explain why you closed this issue?
